### ISSUE TITLE
Split this repo up in micro modules

### ISSUE THREAD

**Issue by jimdebeer** [vigour-io/util#23]
easy transition since we can leave vigour-util as a collector (like lodash) and slowly replace all functionality with specific

**Comment by jimdebeer** [comment]
good start is require, define and hashes

**Comment by shawninder** [comment]
@jimdebeer Any preferred npm package naming convention? Lodash has `lodash.${functionName}` but I don't think we'll want `vigour-util.${functionName}`... Maybe simply `vigour-require`, `vigour-hash`, `vigour-isurl`, `vigour-isemail`, etc? Or perhaps the prefix should be `brisky` instead?

**Comment by jimdebeer** [comment]
vigour-is-url
vigour-is-email
vigour-require
vigour-hash
vigour-doit

**Comment by jimdebeer** [comment]
and if possible make it a non vigour prefixed module thats best 

e.g. is-email

**Comment by jimdebeer** [comment]
also possible to claim a few things if they are inactive
https://www.npmjs.com/package/is-email

pretty funny by segment.io

we could check if they're is email passes our tests if not we can ask them if its ok to replace their module (with ours)

**Comment by jimdebeer** [comment]
vigour-require can become `enhance-require` since it does not exist

**Comment by jimdebeer** [comment]
hash can become fast-hash, or we can ask if we can takeover this https://www.npmjs.com/package/simple-hash

else minimal-hash is also fine (done by the same guy -- if the guy does not resond within 4 weeks we npm will just give us the repo names)

**Comment by jimdebeer** [comment]
i really like the prefix brisky vs vigour -- but in general no prefix is ofcourse BEST

**Comment by jimdebeer** [comment]
@youzi what do you think of prefixing everything with brisky vs vigour (e.g. birsky-state)

**Comment by shawninder** [comment]
Here are the repos we'll need to create to get rid of this one. This is a list of each util currently in this repo specifying a proposed git repo name and npm package name as well as alternatives where the desired name is not available.

In the `available on npm` column, package names are marked:
- `yes` : It's available on npm
- `no*` : It's not available, but perhaps we can just use the existing package
- `no!` : It's not available, but surely we can use the existing package (I've tested it against our current tests)
- `no+` : It's not available, but perhaps we can obtain this package name if we ask nicely
- `no`  : It's not available, the existing package doesn't do the same thing, and there's no chance in hell we're going to obtain that name (too many users of the package for example)
  
  | github repo name | available on npm | available alternative(s) | notes |
  | --- | --- | --- | --- |
  | define | no | util-define, define-props, brisky-define |  |
  | descriptors | yes |  |  |
  | flatten | no | brisky-flatten | Other packages exist which do this, albeit with slightly different usage: obj-flatten, flatten-obj. So we could use those if we're ready to change how we use this everywhere. |
  | hash | no | brisky-hash |  |
  | include | no | incorporate, brisky-include |  |
  | key-hash | yes |  |  |
  | recorder | no+ |  | Only 13 downloads this months, maybe we can convince the owner to give us the name. |
  | regenerator | no | fb-regenerator, brisky-regenerator |  |
  | unflatten | no+ |  | Existing package doesn't support different separators... Let's try to obtain this package name by explaining that our package supercedes theirs. |
  | uuid | no | tiny-uid | Existing package creates much longer strings and has a different API. Let's find another name. Or we could try the `uid` package, which generates ids of variable lengths but defaults to 7... |
  | strip-formatting | yes |  |  |
  | enhance-require | yes |  |  |
  | path-contains | yes |  |  |
  | get-reference | yes |  |  |
  | is-email | no*+ |  | Existing package fails on _weird_ e-mails. Either we support less weirdness or we try to obtain this package name. |
  | is-empty | no | brisky-is-empty (ugly), brempty (only works since brexit) | Existing package doesn't work on Base objects (duh). Let's find another name. |
  | is-hash | yes |  |  |
  | is-node | no* |  | Existing package exports a function... I made a [pull request](https://github.com/MatthewNPM/is-node/pull/1) to correct this. Let's see if they accepts this. |
  | is-number-like | yes |  |  |
  | is-obj | no | is-brisky (maybe this is confusing since regular objects also return true), brisky-is-object | Existing package doesn't treat Base objects instantiated with an empty object as non-objects... This is a bit weird anyways, maybe the test itself should be changed? @jimdebeer |
  | is-plain-obj | no | is-plain | Same as above |
  | is-removed | yes |  |  |
  | is-stream | no! |  | Let's just use the existing package! It even has `isStream.duplex` and `isStream.transform`. YAY! |
  | is-touch | yes |  |  |
  | is-url | no+ |  | Existing package doesn't support `localhost`, ips, or extra options such as `requireProtocol`, which we use. Let's try to obtain this name. |

So @jimdebeer, could you give me some more name ideas? I'm going to wait for your green light to go ahead with any of these.. The ones I'm tempted to do straight away are:

Just do it:
- descriptors
- key-hash
- enhance-require
- path-contains
- get-reference
- is-plain
- is-removed
- is-touch

Write to owners to obtain name:
- unflatten
- is-email
- is-hash
- is-number-like
- is-url

Use other package
- is-stream

What do you think?

**Comment by MatthewSH** [comment]
I think a lot of the things you all are doing are already in existence. Would be best just to try to send pull requests and make the existing packages even better.

**Comment by jimdebeer** [comment]
**is-stream** 
We don't really need to know writable from readable (not important I think) we could also make a pull req to is stream /w entry point writable/readable if its really important  - remove YEEY! 

**is-removed** 
Very specific to vigour-base so maybe call it vigour-base-is-removed (ugly but descriptive) 

**is-plain** 
Also specific for vigour stuff so prob vigour-base-is-plain or something (hopefully we find a better name) is plain is very very important importantly in our stack (perf is 30x faster for our use case since we only need to know if something is not null, not a function and not a Base)

**get-reference**
extremely specific for base as well this is a candidate for deprecation don't think we use it anywhere in our stack (remove would be best!)

**path contains** 
Maybe there is a path contains module already?

Name for the hash utility 
(not the key hash but the modified murmur hash)
**simple-hash** or **minimal-hash** these are not available but not used and not update for 2 years (read npm package name guidelines -- this is something they can help us with) packages are both from the same guy

name for is-hash **is-simple-hash** or **is-minimal-hash** 
description -- simple hash based on murmur hash build for performance

@MatthewSH for sure! best code is no code ;)

**Comment by jimdebeer** [comment]
I would like to check the uid package (we will store uid on every update so length is important there unfortunately)

**Comment by jimdebeer** [comment]
Recorder is a very specific thing for brisky so im fine with brisky-recorder

**Comment by shawninder** [comment]
@jimdebeer 

**is-stream**
We already had `isStream.readable()` and `isStream.writable()` in our util. `is-stream` has them too, as well as `isStream.duplex()`, `isStream.transform()`, and of course, `isStream()`. To me this looks like a perfect drop-in replacement allowing us to kill our own `isStream`. No need for a PR... I'm not sure I understand what you're saying here. Why the PR?

**vigour-base-is-removed**
deal

**vigour-base-is-plain**
I can wait a little to do this one in case we find a better name

**get-reference**
I'll just leave it in `util` for now and call it deprecated

**path-contains**
Our implementation is not exactly like a generic array-contains because it uses `path[i] === key || typeof path[i] === 'string' && path[i].indexOf(':' + key) > 0`. If we can get rid of this `:` thing, then we can surely find another package that does this. If not then I doubt it..

**hash**
`tiny-hash` and `is-tiny-hash` are both available. So are `quick-hash` and `is-quick-hash`. Maybe one of these is easier/faster than trying to obtain `small-hash` or `minimal-hash`?

**Comment by jimdebeer** [comment]
hash
love quick hash

isstream
pr is crap lets use is stream

contains
path : is not nessecary anymore (yeey!)

**Comment by shawninder** [comment]
# Status

## Now available on npm
- [x] vigour-util/descriptors -> **descriptors**
- [x] vigour-util/hash -> **quick-hash**
- [x] vigour-util/is/hash -> **is-quick-hash**
- [x] vigour-util/is/numberlike -> **is-number-like**
- [x] vigour-util/require -> **enhance-require**
- [x] vigour-util/is/touch -> **is-touch**
- [x] vigour-util/keyHash -> **key-hash**
- [x] vigour-util/recorder -> **brisky-recorder**
- [x] vigour-util/is/removed -> **brisky-is-removed**
- [x] vigour-util/strip/formatting -> **strip-formatting**
- [x] vigour-util/is/node -> **is-node** *
- [x] vigour-util/is/number -> **lodash.isfinite** *
- [x] vigour-util/is/stream -> **is-stream** *
- [x] vigour-util/flatten -> **flatten-obj or obj-flatten** *
- [x] vigour-util/regenerator -> **regenerator** *
- [x] **unflatten**
- [x] **is/empty** -> **brisky-is-empty**
- [x] **is/obj** -> **brisky-is-obj**
- [x] **define** -> **define-configurable**
- [x] **get/reference** -> **brisky-get-reference**
- [x] **is/plainobj** -> **brisky-is-plain-obj**
- [x] **uuid** -> **uid** *
- [x] **is/email** -> **nice-is-email** (segmentio/is-email is not responding to my PR)
- [x] **is/url** : **nice-is-url** (segmentio/is-url is not responding to my PR)
- [x] **include** : This one stays in vigour-util

*_: no longer owned by vigour-io_

**Comment by jimdebeer** [comment]
is plainobj --> brisky-is-plain-obj
define-configurable is fine
include lets remove dont think its used anywhere anymore
uuid --> yes need to check perf and length cannot be too long but seems very sensible

**Comment by jimdebeer** [comment]
is-removed and is-empty can become brisky-is-empty and brisky-is-removed (specific) same for get reference brisky-get-reference

**Comment by jimdebeer** [comment]
and brisky-is-obj

**Comment by shawninder** [comment]
What about **is/plainobj**? brisky-is-plain-obj? **brisky-is-plain**?

**Comment by jimdebeer** [comment]
is-fresh-url
is-fresh-email?

**Comment by jimdebeer** [comment]
is-nice-url, is-nice-email

**Comment by jimdebeer** [comment]
is-url-truth

**Comment by jimdebeer** [comment]
is-the-best-url

**Comment by shawninder** [comment]
is-url-fo-sho

**Comment by marcusbesjes** [comment]
@boitewitte is going to put a little "get by path" util we're using across repos

repo name `blend-get-path`
npm name `blend-get-path`

**Comment by marcusbesjes** [comment]
@boitewitte could you add `util` as a label to the `package.json`? might help to group our util type modules

**Comment by marcusbesjes** [comment]
ok little update, not making `blend-get-path` but using `lodash.get`, probably ok to write `null` as default value everywhere.

**Comment by shawninder** [comment]
@marcusbesjes When you say "add `util` as a label to the `package.json`", do you mean to add the word `util` as a keyword? If so I will go around the other utils and make sure they have this as well
